baseURL = "http://www.devlog.host/"
languageCode = "pt-br"
title = "Devlog"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "devlog-unifil"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/css.css"]
  background_color_class = "bg-black"
  recent_posts_number = 4
  filename = "sitemap.xml"
  commentoEnable = true